version: "3"
services:
  node_primary:
    build:
      context: .
      dockerfile: NodeDockerfile
    ports:
      - "8440:1337"
    command: "npm run devServer -- --host node_primary --knownHost node_primary --knownPort 1337"
  node_secondary:
    build:
      context: .
      dockerfile: NodeDockerfile
    command: "npm run devServer -- --knownHost node_primary --knownPort 1337"
    depends_on:
      - node_primary
  client:
  web:
    build:
      context: .
      dockerfile: ClientDockerfile
      dockerfile: WebDockerfile
    ports:
      - "1337:1337"
    depends_on:
      - node_primary
    # volumes:
    #   - .:/home/node/app
    #   - /home/node/app/node_modules/
    command: npm run devClient -- crawl --host node_primary --port 1337 --webPort 1337
    command: npm run devWeb -- --host node_primary --port 1337 --webPort 1337